// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UniRx;


[DiagramInfoAttribute("Game")]
public abstract class PlayerViewBase : EntityViewBase {
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _multiplayer;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public Int32 _parts;
    
    public override System.Type ViewModelType {
        get {
            return typeof(PlayerViewModel);
        }
    }
    
    public PlayerViewModel Player {
        get {
            return ((PlayerViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<PlayerController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
        base.InitializeViewModel(viewModel);
        PlayerViewModel player = ((PlayerViewModel)(viewModel));
        player.multiplayer = this._multiplayer;
        player.parts = this._parts;
    }
    
    public virtual void ExecuteAddMultiplayerPart() {
        this.ExecuteCommand(Player.AddMultiplayerPart);
    }
    
    public virtual void ExecuteAddScore(Int32 arg) {
        this.ExecuteCommand(Player.AddScore, arg);
    }
}

[DiagramInfoAttribute("Game")]
public abstract class EntityViewBase : ViewBase {
    
    public override System.Type ViewModelType {
        get {
            return typeof(EntityViewModel);
        }
    }
    
    public EntityViewModel Entity {
        get {
            return ((EntityViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<EntityController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
    }
    
    public virtual void ExecuteTakeDamage(Int32 arg) {
        this.ExecuteCommand(Entity.TakeDamage, arg);
    }
}

[DiagramInfoAttribute("Game")]
public abstract class EnemyViewBase : EntityViewBase {
    
    public override System.Type ViewModelType {
        get {
            return typeof(EnemyViewModel);
        }
    }
    
    public EnemyViewModel Enemy {
        get {
            return ((EnemyViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<EnemyController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
        base.InitializeViewModel(viewModel);
    }
}

public class PlayerViewViewBase : PlayerViewBase {
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<PlayerController>());
    }
    
    public override void Bind() {
        base.Bind();
    }
}

public partial class PlayerView : PlayerViewViewBase {
}

public class MultiplayerViewViewBase : PlayerViewBase {
    
    [UFToggleGroup("multiplayer")]
    [UnityEngine.HideInInspector()]
    [UFRequireInstanceMethod("multiplayerChanged")]
    public bool _Bindmultiplayer = true;
    
    [UFToggleGroup("parts")]
    [UnityEngine.HideInInspector()]
    [UFRequireInstanceMethod("partsChanged")]
    public bool _Bindparts = true;
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<PlayerController>());
    }
    
    /// Subscribes to the property and is notified anytime the value changes.
    public virtual void multiplayerChanged(Int32 value) {
    }
    
    /// Subscribes to the property and is notified anytime the value changes.
    public virtual void partsChanged(Int32 value) {
    }
    
    public override void Bind() {
        base.Bind();
        if (this._Bindmultiplayer) {
            this.BindProperty(Player._multiplayerProperty, this.multiplayerChanged);
        }
        if (this._Bindparts) {
            this.BindProperty(Player._partsProperty, this.partsChanged);
        }
    }
}

public partial class MultiplayerView : MultiplayerViewViewBase {
}

public class PlayerScoreViewViewBase : PlayerViewBase {
    
    private IDisposable _scoreDisposable;
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<PlayerController>());
    }
    
    public virtual void Resetscore() {
        if (_scoreDisposable != null) _scoreDisposable.Dispose();
        _scoreDisposable = GetscoreObservable().Subscribe(Player._scoreProperty).DisposeWith(this);
    }
    
    protected virtual Int32 Calculatescore() {
        return default(Int32);
    }
    
    protected virtual UniRx.IObservable<Int32> GetscoreObservable() {
        return this.UpdateAsObservable().Select(p => Calculatescore());
    }
    
    public override void Bind() {
        base.Bind();
        Resetscore();
    }
}

public partial class PlayerScoreView : PlayerScoreViewViewBase {
}
