// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UniRx;


[System.SerializableAttribute()]
public sealed partial class GameSceneManagerSettings {
    
    public string[] _Scenes;
}

// <summary>
// The responsibility of this class is to manage the scenes Initialization, Loading, Transitioning, and Unloading.
// </summary>
public class GameSceneManagerBase : SceneManager {
    
    private PlayerController _PlayerController;
    
    private EntityController _EntityController;
    
    private EnemyController _EnemyController;
    
    private BulletController _BulletController;
    
    private DropController _DropController;
    
    private CoinDropController _CoinDropController;
    
    private MultiplierDropController _MultiplierDropController;
    
    private UpgradeController _UpgradeController;
    
    private HealthUpgradeController _HealthUpgradeController;
    
    private DropUpgradeController _DropUpgradeController;
    
    private FireElementController _FireElementController;
    
    private BulletUpgradeController _BulletUpgradeController;
    
    public GameSceneManagerSettings _GameSceneManagerSettings = new GameSceneManagerSettings();
    
    [Inject()]
    public virtual PlayerController PlayerController {
        get {
            if ((this._PlayerController == null)) {
                this._PlayerController = new PlayerController() { Container = Container };
            }
            return this._PlayerController;
        }
        set {
            _PlayerController = value;
        }
    }
    
    [Inject()]
    public virtual EntityController EntityController {
        get {
            if ((this._EntityController == null)) {
                this._EntityController = new EntityController() { Container = Container };
            }
            return this._EntityController;
        }
        set {
            _EntityController = value;
        }
    }
    
    [Inject()]
    public virtual EnemyController EnemyController {
        get {
            if ((this._EnemyController == null)) {
                this._EnemyController = new EnemyController() { Container = Container };
            }
            return this._EnemyController;
        }
        set {
            _EnemyController = value;
        }
    }
    
    [Inject()]
    public virtual BulletController BulletController {
        get {
            if ((this._BulletController == null)) {
                this._BulletController = new BulletController() { Container = Container };
            }
            return this._BulletController;
        }
        set {
            _BulletController = value;
        }
    }
    
    [Inject()]
    public virtual DropController DropController {
        get {
            if ((this._DropController == null)) {
                this._DropController = new DropController() { Container = Container };
            }
            return this._DropController;
        }
        set {
            _DropController = value;
        }
    }
    
    [Inject()]
    public virtual CoinDropController CoinDropController {
        get {
            if ((this._CoinDropController == null)) {
                this._CoinDropController = new CoinDropController() { Container = Container };
            }
            return this._CoinDropController;
        }
        set {
            _CoinDropController = value;
        }
    }
    
    [Inject()]
    public virtual MultiplierDropController MultiplierDropController {
        get {
            if ((this._MultiplierDropController == null)) {
                this._MultiplierDropController = new MultiplierDropController() { Container = Container };
            }
            return this._MultiplierDropController;
        }
        set {
            _MultiplierDropController = value;
        }
    }
    
    [Inject()]
    public virtual UpgradeController UpgradeController {
        get {
            if ((this._UpgradeController == null)) {
                this._UpgradeController = new UpgradeController() { Container = Container };
            }
            return this._UpgradeController;
        }
        set {
            _UpgradeController = value;
        }
    }
    
    [Inject()]
    public virtual HealthUpgradeController HealthUpgradeController {
        get {
            if ((this._HealthUpgradeController == null)) {
                this._HealthUpgradeController = new HealthUpgradeController() { Container = Container };
            }
            return this._HealthUpgradeController;
        }
        set {
            _HealthUpgradeController = value;
        }
    }
    
    [Inject()]
    public virtual DropUpgradeController DropUpgradeController {
        get {
            if ((this._DropUpgradeController == null)) {
                this._DropUpgradeController = new DropUpgradeController() { Container = Container };
            }
            return this._DropUpgradeController;
        }
        set {
            _DropUpgradeController = value;
        }
    }
    
    [Inject()]
    public virtual FireElementController FireElementController {
        get {
            if ((this._FireElementController == null)) {
                this._FireElementController = new FireElementController() { Container = Container };
            }
            return this._FireElementController;
        }
        set {
            _FireElementController = value;
        }
    }
    
    [Inject()]
    public virtual BulletUpgradeController BulletUpgradeController {
        get {
            if ((this._BulletUpgradeController == null)) {
                this._BulletUpgradeController = new BulletUpgradeController() { Container = Container };
            }
            return this._BulletUpgradeController;
        }
        set {
            _BulletUpgradeController = value;
        }
    }
    
    // <summary>
    // This method is the first method to be invoked when the scene first loads. Anything registered here with 'Container' will effectively 
    // be injected on controllers, and instances defined on a subsystem.And example of this would be Container.RegisterInstance<IDataRepository>(new CodeRepository()). Then any property with 
    // the 'Inject' attribute on any controller or view-model will automatically be set by uFrame. 
    // </summary>
    public override void Setup() {
        base.Setup();
        Container.RegisterController<PlayerController>(PlayerController);
        Container.RegisterController<EntityController>(EntityController);
        Container.RegisterController<EnemyController>(EnemyController);
        Container.RegisterController<BulletController>(BulletController);
        Container.RegisterController<DropController>(DropController);
        Container.RegisterController<CoinDropController>(CoinDropController);
        Container.RegisterController<MultiplierDropController>(MultiplierDropController);
        Container.RegisterController<UpgradeController>(UpgradeController);
        Container.RegisterController<HealthUpgradeController>(HealthUpgradeController);
        Container.RegisterController<DropUpgradeController>(DropUpgradeController);
        Container.RegisterController<FireElementController>(FireElementController);
        Container.RegisterController<BulletUpgradeController>(BulletUpgradeController);
        this.Container.InjectAll();
    }
    
    public override void Initialize() {
        base.Initialize();
    }
}
